package com.app.ordenaly.utils;

public enum Permissions {
  READ_ORDERS, UPDATE_ORDER, SAVE_ORDER,
  READ_PRODUCTS, SAVE_PRODUCT, DELETE_PRODUCT, UPDATE_PRODUCT,
  SAVE_TICKET, READ_TICKETS,
  SAVE_USER, READ_USERS, DELETE_USER, UPDATE_USER



}
